export const TYPOGRAPHY = {
	DISPLAY1: "display1",
	DISPLAY2: "display2",
	DISPLAY3: "display3",
	DISPLAY4: "display4",
	HEADING1: "heading1",
	HEADING2: "heading2",
	HEADING3: "heading3",
	HEADING4: "heading4",
	HEADING5: "heading5",
	HEADING6: "heading6",
	SUBTITLE1: "subtitle1",
	SUBTITLE2: "subtitle2",
	BODY1: "body1",
	BODY2: "body2",
	BODY3: "body3",
	BODY4: "body4",
	CODE1: "code1",
	CODE2: "code2",
} as const;
